---

- name: add infrastructure repo
  copy: src="{{ files }}/common/{{ item }}" dest="/etc/yum.repos.d/{{ item }}"
  with_items:
  - infrastructure.repo
  - infrastructure-testing.repo
  tags:
  - config
  - packages
  - yumrepos
