---
# tasks file for bugzilla
#
- name: install eseyman bugzilla 4.4 copr repo
  file: src=eseyman-bugzilla-4.4-epel-7.repo dest=/etc/yum.repos.d/eseyman-bugzilla-4.4-epel-7.repo owner=root group=root
  tags:
  - config
  - packages
  - yumrepos

- name: install needed packages for bugzilla
  yum: pkg={{ item }} state=present
  with_items:
  - bugzilla
  - bugzilla-contrib
  - perl-DBD-Pg
  - perl-Test-Taint
  - perl-XMLRPC-Lite
  tags:
  - packages
  - bugzilla
