---
# tasks file for bugzilla
#

- name: install needed packages for bugzilla
  yum: pkg={{ item }} state=present
  with_items:
  - bugzilla
  - bugzilla-contrib
  - perl-DBD-Pg
  - perl-Test-Taint
  - perl-XMLRPC-Lite
  tags:
  - packages
  - bugzilla
